# Generated by Django 5.0.2 on 2024-03-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cakes', '0001_initial'),
        ('flours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaasketCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='BaasketFlour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flours.flour')),
            ],
        ),
    ]
